### ISSUE TITLE
Dead links on homepage (index.html)

### ISSUE THREAD

**Issue by JVillella** [cusec/cusec.github.io#3]
Hello!

I was on the http://cusec.net/ homepage this morning to subscribe to the newsletter and noticed it was a dead link (together with the blog). Wanted to let you folks know. It's in this paragraph:

"How Do I Stay Informed We try to make that as easy as possible for you. We offer you two ways you can stay informed about CUSEC. You can sign-up to our newsletter or to our blog's Icon for Feed RSS feed. It is recommended you sign-up to both because they don't always include the same information."

If you have up to date links I can submit a PR.

**Comment by alexcoco** [comment]
Hi Julian!

Thanks for pointing that out 😄. That page is pretty old and those links are definitely out of date. We don't maintain a CUSEC blog or RSS anymore but we still have a mailing list. If you'd like to send a PR that would be awesome! Here's the new mailing list signup link: http://eepurl.com/bnJ89
